name: Refresh Badges

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh badges
        uses: b3b00/refreshBadgesAction@v1.0.7
        with:
          repository: 'zuzak/mcp-grocy-api'
          branch: 'dev'
